// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GrocerySystem.Entities
{
    internal partial class Order
    {
        public Order()
        {
            OrderLists = new HashSet<OrderList>();
        }

        [Key]
        public int OrderID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public int? PickerID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RequiredBy { get; set; }
        public bool Delivery { get; set; }
        [Column(TypeName = "money")]
        public decimal SubTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal GST { get; set; }
        /// <summary>
        /// **N**ew Order Placed, **A**ssigned to Picker, **R**ready (Picked), **O**ut on Delivery, **D**elivered, **P**icked up by Customer
        /// </summary>
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastStatusUpdate { get; set; }

        [ForeignKey(nameof(CustomerID))]
        [InverseProperty("Orders")]
        public virtual Customer Customer { get; set; }
        [ForeignKey(nameof(StoreID))]
        [InverseProperty("Orders")]
        public virtual Store Store { get; set; }
        [InverseProperty(nameof(OrderList.Order))]
        public virtual ICollection<OrderList> OrderLists { get; set; }
    }
}